apiVersion: v1
kind: Service
metadata:
  name: activemq
  labels:
    name: activemq
spec:
  type: NodePort
  ports:
  - port: 8161
    name: http
    nodePort: 31010
  - port: 61616
    name: tcp
    nodePort: 31011
  - port: 61613
    name: stomp
    nodePort: 31012
  selector:
    name: activemq
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: activemq
  labels:
    name: activemq
spec:
  replicas: 1
  selector:
    name: activemq
  template:
    metadata:
      labels:
        name: activemq
    spec:
      containers:
      - name: activemq
        image: webcenter/activemq
        ports:
        - containerPort: 8161
        - containerPort: 61616
        - containerPort: 61613
        env:
          - name: ACTIVEMQ_SERIALIZABLE_PACKAGES
            value: '*'
          - name: ACTIVEMQ_STATIC_QUEUES
            value: kieker
---
apiVersion: v1
kind: Service
metadata:
  name: kls
  labels:
    name: kls
spec:
  type: NodePort
  ports:
  - port: 8080
    name: kls-http
    nodePort: 31020
  selector:
    name: kls
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kls
  labels:
    name: kls
spec:
  replicas: 1
  selector:
    name: kls
  template:
    metadata:
      labels:
        name: kls
    spec:
      containers:
      - name: kls
        image: kieker/kieker-logging-server:0.1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: KLS_LOGGER_ENABLED
            value: "false"
          - name: KLS_JMS_HOST
            value: activemq
          - name: KLS_JMS_PORT
            value: '61616'
          - name: KLS_JMS_QUEUE
            value: kieker
          - name: KLS_INFLUXDB_ENABLED
            value: "true"
          - name: KLS_INFLUXDB_URL
            value: 'http://influxdb'
          - name: KLS_INFLUXDB_PORT
            value: '8086'
          - name: KLS_INFLUXDB_USERNAME
            value: root
          - name: KLS_INFLUXDB_PASSWORD
            value: root
          - name: KLS_INFLUXDB_DATABASE_NAME
            value: kieker
