apiVersion: v1
kind: Service
metadata:
  name: hora
  labels:
    name: hora
spec:
  type: NodePort
  ports:
  - port: 8080
    name: http
    nodePort: 31100
  selector:
    name: hora
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: hora
  labels:
    name: hora
spec:
  replicas: 1
  selector:
    name: hora
  template:
    metadata:
      labels:
        name: hora
    spec:
      containers:
      - name: hora
        image: teeratpitakrat/hora:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: HORA_CFP_RESPONSETIME_THRESHOLD
            value: "100ms"
          - name: HORA_CFP_RESPONSETIME_HISTORY
            value: "30m"
          - name: HORA_PREDICTION_LEADTIME
            value: "10m"
          - name: HORA_RSERVE_HOSTNAME
            value: "rserve"
          - name: HORA_RSERVE_PORT
            value: "6311"
          - name: HORA_INFLUXDB_ADDR
            value: "http://influxdb:8086"
          - name: HORA_INFLUXDB_USERNAME
            value: "root"
          - name: HORA_INFLUXDB_PASSWORD
            value: "root"
          - name: HORA_INFLUXDB_BATCH
            value: "FALSE"
