apiVersion: v1
kind: Service
metadata:
  name: activemq
  labels:
    name: activemq
spec:
  type: NodePort
  ports:
  - port: 8161
    name: http
    nodePort: 31010
  - port: 61616
    name: tcp
    nodePort: 31011
  - port: 61613
    name: stomp
    nodePort: 31012
  selector:
    name: activemq
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: activemq
  labels:
    name: activemq
spec:
  replicas: 1
  selector:
    name: activemq
  template:
    metadata:
      labels:
        name: activemq
    spec:
      containers:
      - name: activemq
        image: webcenter/activemq
        ports:
        - containerPort: 8161
        - containerPort: 61616
        - containerPort: 61613
        env:
          - name: ACTIVEMQ_SERIALIZABLE_PACKAGES
            value: '*'
          - name: ACTIVEMQ_STATIC_QUEUES
            value: kieker
